name: Deploy Glue Tables
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      - name: Delete existing stack if in ROLLBACK_COMPLETE
        run: |
          if aws cloudformation describe-stacks --stack-name glue-table-stack --region ap-southeast-2 2>&1 | grep -q 'ROLLBACK_COMPLETE'; then
            aws cloudformation delete-stack --stack-name glue-table-stack --region ap-southeast-2
            aws cloudformation wait stack-delete-complete --stack-name glue-table-stack --region ap-southeast-2
          fi
      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template --template-body file://cfm.yaml
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy --template-file cfm.yaml --stack-name glue-table-stack --capabilities CAPABILITY_NAMED_IAM --region ap-southeast-2 --no-fail-on-empty-changeset
      - name: Check stack events on failure
        if: failure()
        run: |
          aws cloudformation describe-stack-events --stack-name glue-table-stack --region ap-southeast-2
